/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 计算离群值
*/
export function outliers(numbers: Array<number>): Array<number>
/**
 * 计算变异系数
*/
export function coefficientOfVariation(numbers: Array<number>): number
